{{- if not .Values.aomarketBot.createSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-external-secret
spec:
  refreshInterval: {{ .Values.aomarketBot.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.aomarketBot.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.aomarketBot.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Release.Name }}-secret
    creationPolicy: Owner
  data:
    {{- if eq .Values.aomarketBot.database.mode "url" }}
    - secretKey: database-url
      remoteRef:
        key: {{ .Values.aomarketBot.externalSecret.remoteKey.databaseUrl }}
    {{- end }}
    - secretKey: ao-password
      remoteRef:
        key: {{ .Values.aomarketBot.externalSecret.remoteKey.aoPassword }}
{{- end }}
