{{- if .Values.aomarketBot.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  database-url: {{ required "aomarketBot.secret.databaseUrl is required" .Values.aomarketBot.secret.databaseUrl | quote }}
  ao-login: {{ .Values.aomarketBot.secret.aoLogin | quote }}
  ao-password: {{ .Values.aomarketBot.secret.aoPassword | quote }}
{{- end }}
