apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-serviceaccount
{{- with .Values.aomarketBot.imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
