"""add aodb_lookup_backoff table

Revision ID: d9aefd01bbb0
Revises: 61dca6f1a427
Create Date: 2026-08-17 15:37:49.802791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9aefd01bbb0'
down_revision: Union[str, Sequence[str], None] = '61dca6f1a427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aodb_lookup_backoff',
    sa.Column('aoid', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('failure_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('aoid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aodb_lookup_backoff')
    # ### end Alembic commands ###
