"""initial schema

Revision ID: ef9f279ce6b5
Revises: 
Create Date: 2026-08-08 12:49:54.192189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9f279ce6b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_pending_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player', sa.Text(), nullable=False),
    sa.Column('aoid', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_seen_orders',
    sa.Column('aoid', sa.BigInteger(), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('aoid', 'fingerprint')
    )
    op.create_table('market_user_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('aoid', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_user_actions_player_created', 'market_user_actions', ['player', 'created_at'], unique=False)
    op.create_table('market_users',
    sa.Column('player', sa.Text(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('player')
    )
    op.create_table('market_watch',
    sa.Column('aoid', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ql', sa.Integer(), nullable=False),
    sa.Column('icon', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_polled', sa.DateTime(timezone=True), server_default='-infinity', nullable=False),
    sa.Column('auto_tracked', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('aoid')
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("value_type IN ('bool','int','float','str')", name='ck_settings_value_type'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('market_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aoid', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sell_count', sa.Integer(), nullable=False),
    sa.Column('buy_count', sa.Integer(), nullable=False),
    sa.Column('min_sell_price', sa.BigInteger(), nullable=True),
    sa.Column('max_buy_price', sa.BigInteger(), nullable=True),
    sa.Column('avg_sell_price', sa.Numeric(), nullable=True),
    sa.Column('avg_buy_price', sa.Numeric(), nullable=True),
    sa.Column('anchor_sell_count', sa.Integer(), nullable=True),
    sa.Column('anchor_buy_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aoid'], ['market_watch.aoid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_history_aoid_ts', 'market_history', ['aoid', 'ts'], unique=False)
    op.create_table('market_subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player', sa.Text(), nullable=False),
    sa.Column('aoid', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='subscription_side'), nullable=True),
    sa.Column('min_price', sa.BigInteger(), nullable=True),
    sa.Column('max_price', sa.BigInteger(), nullable=True),
    sa.Column('min_ql', sa.Integer(), nullable=True),
    sa.Column('max_ql', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aoid'], ['market_watch.aoid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player'], ['market_users.player'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player', 'aoid', name='uq_market_subscriptions_player_aoid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_subscriptions')
    op.drop_index('ix_market_history_aoid_ts', table_name='market_history')
    op.drop_table('market_history')
    op.drop_table('settings')
    op.drop_table('market_watch')
    op.drop_table('market_users')
    op.drop_index('ix_market_user_actions_player_created', table_name='market_user_actions')
    op.drop_table('market_user_actions')
    op.drop_table('market_seen_orders')
    op.drop_table('market_pending_alerts')
    # ### end Alembic commands ###
